# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqRxjMuvbu_lwi6CrvJaIAWnZW6jllO3
"""

import pandas as pd

#Read the dataset to python environment
#Display the columns in the dataset

data = pd.read_excel('/content/iris.xls')
data

data.info()

#Calculate the mean of each column of the dataset.

data['SL'].mean()

data['SW'].mean()

data['PL'].mean()

data['PW'].mean()

data.describe() #mean value togather

#Check for the null values present in the dataset.

data.isna()

data.isna().sum()

#Perform meaningful visualizations using the dataset. Bring at least 3 visualizations.

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

data.head(10)

plt.title('Iris Description')
plt.xlabel('Flower')
plt.ylabel('Sepal Length')
plt.bar(data['Classification'],data['SL'],width=0.2)

plt.boxplot(data['PL']);

